### ISSUE TITLE
Stop at "Downloading OS package info..."

### ISSUE THREAD

**Issue by Pathsis** [AsahiLinux/docs#113]
Hello. I'm having trouble downloading the "Downloading OS package info..." step! 

 I am experiencing insurmountable difficulties with the "Downloading OS package info..." step. I am unable to continue and receive the following message instead:

```shell
Downloading OS package info...
root        : ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 1058, in <module>
    InstallerMain(installer_version).main()
  File "/private/tmp/asahi-install/main.py", line 866, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 1021, in main_loop
    return self.action_install_into_free(parts_free)
  File "/private/tmp/asahi-install/main.py", line 292, in action_install_into_free
    self.osins.load_package()
  File "/private/tmp/asahi-install/osinstall.py", line 47, in load_package
    self.ucache = urlcache.URLCache(package)
  File "/private/tmp/asahi-install/urlcache.py", line 26, in __init__
    self.size = self.get_size()
  File "/private/tmp/asahi-install/urlcache.py", line 67, in get_size
    con.request("HEAD", self.url.path, headers={"Connection":" keep-alive"})
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1426, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer
If you need to file a bug report, please attach the log file:
  /private/tmp/asahi-install/installer.log
```

 This problem is encountered regardless of whether a VPN is used or not.

**Comment by xieweideng** [comment]
Hi do you fix this problem? I'm facing the same problem. I have no idea about this at all.

**Comment by xieweideng** [comment]
I solved this problem by switching VPNs and I'm currently using sing-box on my mac
