### ISSUE TITLE
Storage System Verify or Repair Failed

### ISSUE THREAD

**Issue by maximalisms** [AsahiLinux/docs#12]
Getting this return after setting the parameters for the partition resize:

Running MacBook Air M1 2020

The container /dev/disk0s2 could not be verified completely
Storage system check exit code is 8
Error: -69716: Storage system verify or repair failed
Failed to run process: {cmd}
root        : ERROR    Process execution failed
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 802, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 654, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 774, in main_loop
    return self.action_resize(parts_resizable)
  File "/private/tmp/asahi-install/main.py", line 594, in action_resize
    self.dutil.resizeContainer(target.name, val)
  File "/private/tmp/asahi-install/diskutil.py", line 191, in resizeContainer
    self.action("apfs", "resizeContainer", name, size, verbose=2)
  File "/private/tmp/asahi-install/diskutil.py", line 37, in action
    subprocess.run(["diskutil"] + list(args), check=True)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '116980187136']' returned non-zero exit status 1.

**Comment by stapelberg** [comment]
Rebooting into recovery (hold down power button until the spinner appears), launching disk utility and using the “first aid” button has fixed this error for me.

**Comment by maximalisms** [comment]
> Rebooting into recovery (hold down power button until the spinner appears), launching disk utility and using the “first aid” button has fixed this error for me.

I ended up re-formatting and re-partitioning the drive which ended up fixing it. Another user had the same issue and was solved doing this same thing. [](https://github.com/AsahiLinux/asahi-installer/issues/29)

**Comment by DaviRain-Su** [comment]
> > Rebooting into recovery (hold down power button until the spinner appears), launching disk utility and using the “first aid” button has fixed this error for me.
> 
> I ended up re-formatting and re-partitioning the drive which ended up fixing it. Another user had the same issue and was solved doing this same thing.

If you do this, the original data will be lost, this is not good ah.

**Comment by maximalisms** [comment]
> > > Rebooting into recovery (hold down power button until the spinner appears), launching disk utility and using the “first aid” button has fixed this error for me.
> > 
> > 
> > I ended up re-formatting and re-partitioning the drive which ended up fixing it. Another user had the same issue and was solved doing this same thing.
> 
> If you do this, the original data will be lost, this is not good ah.

If first aid fails to do its job, it may be the only way to fix this issue though. Needless to say it's important to put any important data onto a separate drive.

**Comment by DaviRain-Su** [comment]
> > > > Rebooting into recovery (hold down power button until the spinner appears), launching disk utility and using the “first aid” button has fixed this error for me.
> > > 
> > > 
> > > I ended up re-formatting and re-partitioning the drive which ended up fixing it. Another user had the same issue and was solved doing this same thing.
> > 
> > 
> > If you do this, the original data will be lost, this is not good ah.
> 
> If first aid fails to do its job (which it will in some cases) , it may be the only way to fix this issue though. Needless to say it's important to put any important data onto a separate drive.

Hmmmm understand what you mean, I am trying to initialize the factory settings after backing up.

**Comment by DavidBuchanan314** [comment]
> > Rebooting into recovery (hold down power button until the spinner appears), launching disk utility and using the “first aid” button has fixed this error for me.
> 
> I've tried this on my MBP M1, but it still won't work after repair. Any idea for solving this without complete reinstallation?

I had a similar issue, where `/dev/disk3s5` had warnings that wouldn't go away, and I solved it as follows:

1. Boot into recovery and open a terminal
2. `diskutil unmountdisk /dev/disk3`
3. `fsck_apfs /dev/disk3` (and hit y in response to the various prompts)

I believe unmounting was the important part.
