### ISSUE TITLE
Disk resizing error

### ISSUE THREAD

**Issue by Ilfeni** [AsahiLinux/docs#19]
I was installing Asahi and when I arrived at the disk resizing part I was confronted to this message:
Failed to run process: diskutil apfs resizeContainer disk0s2 429998997504
root        : ERROR    Process execution failed
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 820, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 672, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 792, in main_loop
    return self.action_resize(parts_resizable)
  File "/private/tmp/asahi-install/main.py", line 612, in action_resize
    self.dutil.resizeContainer(target.name, val)
  File "/private/tmp/asahi-install/diskutil.py", line 208, in resizeContainer
    self.action("apfs", "resizeContainer", name, size, verbose=2)
  File "/private/tmp/asahi-install/diskutil.py", line 38, in action
    subprocess.run(["diskutil"] + list(args), check=True)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '429998997504']' returned non-zero exit status 1.
If you need to file a bug report, please attach the log file
What can I do
ps: I tried first aid on the disk it didn't work

**Comment by Catcatcher33** [comment]
Hey, I'm not part of the team but I've noticed this issue being raised quite a bit. Someone's already answered it here: https://github.com/AsahiLinux/docs/issues/16#issuecomment-1081995997

Let me know if it works!

**Comment by Catcatcher33** [comment]
Also, did you perhaps run first aid from the GUI? When my container was being resized, an issue was raised due to internal corruption, which first aid itself could not fix alone. As a result I had to enter the terminal in Recovery mode and manually perform the repair (typing in the necessary commands that First Aid sort of skips).

**Comment by Ilfeni** [comment]
I did as said in the issue 16 and at first it seemed to operate as usual but after a little freeze here's what it shows:
The container /dev/disk0s2 could not be verified completely
Storage system check exit code is 8
Error: -69716: Storage system verify or repair failed
Failed to run process: diskutil apfs resizeContainer disk0s2 370788007936
root        : ERROR    Process execution failed
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 820, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 672, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 792, in main_loop
    return self.action_resize(parts_resizable)
  File "/private/tmp/asahi-install/main.py", line 612, in action_resize
    self.dutil.resizeContainer(target.name, val)
  File "/private/tmp/asahi-install/diskutil.py", line 208, in resizeContainer
    self.action("apfs", "resizeContainer", name, size, verbose=2)
  File "/private/tmp/asahi-install/diskutil.py", line 38, in action
    subprocess.run(["diskutil"] + list(args), check=True)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '370788007936']' returned non-zero exit status 1.
