### ISSUE TITLE
Exceeded maximum retries downloading data.

### ISSUE THREAD

**Issue by AbuTabla** [AsahiLinux/docs#59]
I've tried multiple times to install, some solutions I've tried:
1) Reset to factory
2) Downgrade to Monetary 
3) Different Wi-Fi

yet still get this error during the OS install:

`

Using macOS 12.3 for OS firmware

Downloading macOS OS package info...
- 

Creating new stub macOS named Asahi Linux
Installing stub macOS into disk0s5 (Asahi Linux)
Preparing target volumes...
Checking volumes...
Beginning stub OS install...
| 
Setting up System volume...

Setting up Data volume...
Setting up Preboot volume...
/ 100.00% 
Setting up Recovery volume...
\ 100.00% 
Wrapping up...

Stub OS installation complete.

Adding partition EFI (500.17 MB)...
  Formatting as FAT...
Adding partition Root (168.57 GB)...
Collecting firmware...
Installing OS...
  Copying from esp into disk0s4 partition...
Error downloading data (IncompleteRead(6291456 bytes read, 2097152 more expected)), retrying... (1/10)
Error downloading data (IncompleteRead(6291456 bytes read, 2097152 more expected)), retrying... (2/10)
Error downloading data (IncompleteRead(6291456 bytes read, 2097152 more expected)), retrying... (3/10)
Error downloading data (IncompleteRead(6291456 bytes read, 2097152 more expected)), retrying... (4/10)
Error downloading data (IncompleteRead(6291456 bytes read, 2097152 more expected)), retrying... (5/10)
Error downloading data (IncompleteRead(6291456 bytes read, 2097152 more expected)), retrying... (6/10)
Error downloading data (IncompleteRead(6291456 bytes read, 2097152 more expected)), retrying... (7/10)
Error downloading data (IncompleteRead(6291456 bytes read, 2097152 more expected)), retrying... (8/10)
Error downloading data (IncompleteRead(6291456 bytes read, 2097152 more expected)), retrying... (9/10)
Error downloading data (IncompleteRead(6291456 bytes read, 2097152 more expected)), retrying... (10/10)
Exceeded maximum retries downloading data.
root        : ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 1054, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 865, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 1017, in main_loop
    return self.action_install_into_free(parts_free)
  File "/private/tmp/asahi-install/main.py", line 307, in action_install_into_free
    self.do_install(os_size)
  File "/private/tmp/asahi-install/main.py", line 426, in do_install
    self.osins.install(self.ins)
  File "/private/tmp/asahi-install/osinstall.py", line 122, in install
    self.extract_tree(source, mountpoint)
  File "/private/tmp/asahi-install/util.py", line 198, in extract_tree
    self.extract_file(name, destpath)
  File "/private/tmp/asahi-install/util.py", line 162, in extract_file
    with self.pkg.open(src) as sfd, \
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 1518, in open
    fheader = zef_file.read(sizeFileHeader)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 742, in read
    data = self._file.read(n)
  File "/private/tmp/asahi-install/urlcache.py", line 120, in read
    d.append(self.get_block(blk, readahead).data)
  File "/private/tmp/asahi-install/urlcache.py", line 73, in get_block
    data = self.get_partial(off, size)
  File "/private/tmp/asahi-install/urlcache.py", line 44, in get_partial
    d = fd.read()
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 472, in read
    s = self._safe_read(self.length)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 615, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(6291456 bytes read, 2097152 more expected)
If you need to file a bug report, please attach the log file:
  /private/tmp/asahi-install/installer.log
`

**Comment by marcan** [comment]
Duplicate.
