### ISSUE TITLE
How to fix virt-manager in Asahi Fedora?

### ISSUE THREAD

**Issue by xet7** [AsahiLinux/docs#88]
Hi,
at Asahi Fedora Remix, virt-manager can not open remote VNC desktop via SSH,
it shows this error. I use virt-manager for remote developing at donated bare metal servers.
Is it possible to fix this? Or is there some more appropriate bugtracker somewhere?

```
Error when starting info: could not get a reference to type class

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/vmwindow.py", line 40, in get_instance
    cls._instances[key] = vmmVMWindow(vm)
                          ^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtManager/vmwindow.py", line 83, in __init__
    self._details = vmmDetails(self.vm, self.builder, self.topwin,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtManager/details/details.py", line 389, in __init__
    self._init_details()
  File "/usr/share/virt-manager/virtManager/details/details.py", line 695, in _init_details
    self._os_list = vmmOSList()
                    ^^^^^^^^^^^
  File "/usr/share/virt-manager/virtManager/oslist.py", line 44, in __init__
    self._init_state()
  File "/usr/share/virt-manager/virtManager/oslist.py", line 60, in _init_state
    all_os = virtinst.OSDB.list_os(sortkey="label")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtinst/osdict.py", line 158, in list_os
    self._os_db.get_os_list().get_elements()]
    ^^^^^^^^^^^
  File "/usr/share/virt-manager/virtinst/osdict.py", line 86, in _os_db
    return self._os_loader.get_db()
           ^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtinst/osdict.py", line 78, in _os_loader
    loader = Libosinfo.Loader()
             ^^^^^^^^^^^^^^^^^^
TypeError: could not get a reference to type class
```

**Comment by Capta1nT0ad** [comment]
From a few sources online, I found others fixed a similar issue by navigating to View and changing the view from Spice to VNC.

As this is most likely completely outside of the scope of Asahi Linux, yes, it would be more appropriate to post this kind of 'issue' report someplace else, such as a virt-manager-specific bug/issue tracker.

**Comment by xet7** [comment]
@Capta1nT0ad 

Changing to VNC did not work at Asahi Fedora.

I changed from Asahi Fedora to Asahi Ubuntu, where virt-manager works correctly.
