### ISSUE TITLE
m1 Mac mini

### ISSUE THREAD

**Issue by terese0815** [AsahiLinux/docs#91]
Hi. I'm running in a strange error directly at the start of the installation

 ~/V/myportrait/server-ts │ frontEND ⇡1  cat /private/tmp/asahi-install/installer.log          ✔ │ 4s │ 18:36:31
12-14 18:36 root         INFO     Startup
12-14 18:36 root         INFO     Environment:
12-14 18:36 root         INFO       INSTALLER_BASE=https://cdn.asahilinux.org/installer
12-14 18:36 root         INFO       INSTALLER_DATA=https://fedora-asahi-remix.org/installer_data.json
12-14 18:36 root         INFO       REPO_BASE=https://fedora-asahi-remix.org
12-14 18:36 root         INFO       IPSW_BASE=None
12-14 18:36 root         INFO       EXPERT=None
12-14 18:36 root         INFO       REPORT=https://stats.asahilinux.org/report
12-14 18:36 root         INFO       REPORT_TAG=fedora-prod
12-14 18:36 root         INFO     Version: v0.6.24
12-14 18:36 root         INFO     MSG: Welcome to the Asahi Linux installer!
12-14 18:36 root         INFO     MSG: This installer will guide you through the process of setting up
12-14 18:36 root         INFO     MSG: Asahi Linux on your Mac.
12-14 18:36 root         INFO     MSG: Please make sure you are familiar with our documentation at:
12-14 18:36 root         INFO     MSG:   https://alx.sh/w
12-14 18:36 root         INFO     MSG: Press enter to continue.
12-14 18:36 root         INFO     MSG: Collecting system information...
12-14 18:36 root         ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 1058, in <module>
    InstallerMain(installer_version).main()
  File "/private/tmp/asahi-install/main.py", line 831, in main
    self.sysinfo = system.SystemInfo()
  File "/private/tmp/asahi-install/system.py", line 8, in __init__
    self.fetch()
  File "/private/tmp/asahi-install/system.py", line 18, in fetch
    self.ioservice = plistlib.loads(result.stdout)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/plistlib.py", line 883, in loads
    return load(fp, fmt=fmt, dict_type=dict_type)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/plistlib.py", line 875, in load
    return p.parse(fp)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/plistlib.py", line 177, in parse
    self.parser.ParseFile(fileobj)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 161092, column 35
12-14 18:36 root         INFO     MSG: If you need to file a bug report, please attach the log file:
12-14 18:36 root         INFO     MSG:   /private/tmp/asahi-install/installer.log

Has someone an idea what this is?

**Comment by potirlon** [comment]
Hello !
I have the same issue on Mac mini M2:
```log
12-25 20:16 root         INFO     Startup
12-25 20:16 root         INFO     Environment:
12-25 20:16 root         INFO       INSTALLER_BASE=https://cdn.asahilinux.org/installer
12-25 20:16 root         INFO       INSTALLER_DATA=https://github.com/AsahiLinux/asahi-installer/raw/prod/data/installer_data.json
12-25 20:16 root         INFO       REPO_BASE=https://cdn.asahilinux.org
12-25 20:16 root         INFO       IPSW_BASE=None
12-25 20:16 root         INFO       EXPERT=None
12-25 20:16 root         INFO       REPORT=https://stats.asahilinux.org/report
12-25 20:16 root         INFO       REPORT_TAG=alx-prod
12-25 20:16 root         INFO     Version: v0.7.1
12-25 20:16 root         INFO     MSG: Welcome to the Asahi Linux installer!
12-25 20:16 root         INFO     MSG: This installer will guide you through the process of setting up
12-25 20:16 root         INFO     MSG: Asahi Linux on your Mac.
12-25 20:16 root         INFO     MSG: Please make sure you are familiar with our documentation at:
12-25 20:16 root         INFO     MSG:   [34;1mhttps://alx.sh/w[m[m
12-25 20:16 root         INFO     MSG: Press enter to continue.
12-25 20:17 root         INFO     MSG: Collecting system information...
12-25 20:17 root         ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 1058, in <module>
    InstallerMain(installer_version).main()
  File "/private/tmp/asahi-install/main.py", line 831, in main
    self.sysinfo = system.SystemInfo()
  File "/private/tmp/asahi-install/system.py", line 8, in __init__
    self.fetch()
  File "/private/tmp/asahi-install/system.py", line 18, in fetch
    self.ioservice = plistlib.loads(result.stdout)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/plistlib.py", line 883, in loads
    return load(fp, fmt=fmt, dict_type=dict_type)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/plistlib.py", line 875, in load
    return p.parse(fp)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/plistlib.py", line 177, in parse
    self.parser.ParseFile(fileobj)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 289457, column 34
12-25 20:17 root         INFO     MSG: If you need to file a bug report, please attach the log file:
12-25 20:17 root         INFO     MSG:   /private/tmp/asahi-install/installer.log
```
For what I saw, it might be due to a too long xml file generated by the command `ioreg -alp IOService` (around 15 Mo)

**Comment by terese0815** [comment]
Strange. Do you run some third party backup system?

**Comment by potirlon** [comment]
No I didn't run any backup system, is there any usefull data that I can send to you ?

**Comment by MyztikJenz** [comment]
My son and I just ran into this problem... turns out his keyboard had Chinese characters in the manufacture's name, which causes the output from `ioreg` to be mangled and plistlib chokes. Couldn't find a bug on Python for this, so we worked around it by using a different keyboard for the install.

**Comment by zeph** [comment]
@potirlon is this still happening? I installed my `Mac Mini M2 Pro` the other week, following the installation step by step, and I did not run into this... are you doing something particular/unexpected during the installation?

I had a plain box, never partitioned before, I followed the instructions to resize OsX and that's it. No issues
